from enum import Enum


class EntitiesActions(Enum):
    ATTACK_ACTION = 1
    DEFEND_ACTION = 2
    OPEN_INVENTORY = 3
    OPEN_HELP = 4
    OPEN_SHOP = 5
    MOVE_ACTION = 6
    BUYING_HEALING_POTION = 7
    NOT_BUYING = 8
    CONSUME_HEALING_POTION = 9
    CONSUME_FLOWER_ATTACK = 10
    FLOWER_ATTACK = 11